stylish-haskell -i .\\src\\CDCL\\Algorithm.hs
stylish-haskell -i .\\src\\CDCL\\Types.hs
stylish-haskell -i .\\src\\CDCL\\UnitPropagation.hs
stylish-haskell -i .\\src\\CDCL\\Decisionalalgorithm.hs
stylish-haskell -i .\\src\\CDCL\\MapLogic.hs
stylish-haskell -i .\\src\\CDCL\\Conflict.hs
stylish-haskell -i .\\src\\CDCL\\CDCLFilereader.hs
stylish-haskell -i .\\test\\AlgorithmSpec.hs
stylish-haskell -i .\\app\\Main.hs
